baseurl = "https://nekonull.me/"
languageCode = "zh-cn"
theme = "manis"
paginate = 20
defaultContentLanguage = "zh"
hasCJKLanguage = true
rssLimit = 25

  # Code Highlighting (Chroma)
# pygmentsCodeFences = true
# pygmentsUseClasses = true

disqusShortname = "nekonull"

googleAnalytics = "G-R01JLDY2KE"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # dir name of your blog content (default is `content/posts`)
  #contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  #themeColor = "blue"
  # if you set this to 0, only submenu trigger will be visible
  #showMenuItems = 5
  # set theme to full screen width
  #fullWidthTheme = false
  # center theme with default width
  #centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  mainSections = ["posts"]
  workSections = ["share"]
  tilSections = ["til"]
  latestCount = 5
  utterancesTheme = "github-dark"
  github = "https://github.com/jerrylususu/"
  linkedin = "https://www.linkedin.com/in/%E4%B9%8B%E7%9D%BF-%E5%8D%A2-8779351b2/"
  disqusSections = ["posts","share","archive"]

[params.giscus]
    repo = "jerrylususu/jerrylususu.github.io"
    repoId = "MDEwOlJlcG9zaXRvcnkxNDM1MTk3NDY="
    category = "Blog Comments"
    categoryID = "DIC_kwDOCI3wAs4CZNcG"
    mapping = "pathname"
    reactions = true
    inputPosition = "top"
    theme = "preferred-color-scheme"
    strictMatching = true
    lazyLoading = true
    emitMetadata = false
    lang = "zh-CN"

[languages]

  [languages.zh]
    languageCode = "zh-cn"
    languageName = "简体中文"
    title = "Nekonull's Garden"
    subtitle = "Always read. Mostly hack. Sometimes write."
    tagline = "Always read. Mostly hack. Sometimes write."
    keywords = ""
    copyright = "CC-BY-SA-4.0"

    [languages.zh.params.logo]
      logoText = "Nekonull's Garden"
      logoHomeLink = "/"

    [languages.zh.menu]
      [[languages.zh.menu.main]]
        identifier = "about"
        name = "关于"
        url = "/about"
      [[languages.zh.menu.main]]
        identifier = "project"
        name = "项目"
        url = "/project"
      [[languages.zh.menu.main]]
        identifier = "posts"
        name = "长文"
        url = "/posts"
      [[languages.zh.menu.main]]
        identifier = "archive"
        name = "存档"
        url = "/archive"
      [[languages.zh.menu.main]]
        identifier = "share"
        name = "短文"
        url = "/share"
      [[languages.zh.menu.main]]
        identifier = "til"
        name = "TIL"
        url = "/til"
      [[languages.zh.menu.main]]
        identifier = "tag"
        name = "标签"
        url = "/tags"


  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    title = "Nekonull's Garden"
    subtitle = "Always read. Mostly hack. Sometimes write."
    tagline = "Always read. Mostly hack. Sometimes write."
    keywords = ""
    copyright = "CC-BY-SA-4.0"

    [languages.en.params.logo]
      logoText = "Nekonull's Garden"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "project"
        name = "Project"
        url = "/project"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "archive"
        name = "Archive"
        url = "/archive"
      [[languages.en.menu.main]]
        identifier = "share"
        name = "Share"
        url = "/share"
      [[languages.en.menu.main]]
        identifier = "til"
        name = "TIL"
        url = "/til"
      [[languages.en.menu.main]]
        identifier = "tag"
        name = "Tag"
        url = "/tags"